spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/theatre
    username: frynet
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

server:
  error:
    include-message: always
  port: 8080

endpoint:
  url: "http://localhost:${server.port}"
